name: plant_it_fe
description: ""

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.4
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0
  image_picker: ^1.2.1
  google_sign_in: ^7.2.0
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: GmarketSansTTF
      fonts:
        - asset: assets/fonts/GmarketSansTTFBold.ttf
          weight: 700
        - asset: assets/fonts/GmarketSansTTFMedium.ttf
          weight: 500
        - asset: assets/fonts/GmarketSansTTFLight.ttf
          weight: 300
    - family: twaySky
      fonts:
        - asset: assets/fonts/tway_sky.ttf