// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2QIInvz6sq5kiHo1o_i2a1_fmeF2H6IM',
    appId: '1:9146247512:android:f69248183f0cbf5d059d2d',
    messagingSenderId: '9146247512',
    projectId: 'capstone-b19e0',
    storageBucket: 'capstone-b19e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXbgssSRDMlV02VFfqv3WlWKbsP4Gpd_Y',
    appId: '1:9146247512:ios:cf7342d795bba190059d2d',
    messagingSenderId: '9146247512',
    projectId: 'capstone-b19e0',
    storageBucket: 'capstone-b19e0.firebasestorage.app',
    androidClientId: '9146247512-6cpflhcg2tauit35cqblcgub13ft8er4.apps.googleusercontent.com',
    iosClientId: '9146247512-rs6fohk0kpgqksr5vr2cnl4fc0aha4so.apps.googleusercontent.com',
    iosBundleId: 'dev.siyoung.growve',
  );
}
