name: growve_web
description: ""

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/growve_icon.png
    - assets/fonts/

  fonts:
    - family: GmarketSansTTF
      fonts:
        - asset: assets/fonts/GmarketSansTTFBold.ttf
          weight: 700
        - asset: assets/fonts/GmarketSansTTFMedium.ttf
          weight: 500
        - asset: assets/fonts/GmarketSansTTFLight.ttf
          weight: 300
    - family: twaySky
      fonts:
        - asset: assets/fonts/tway_sky.ttf